# coding: utf-8

"""
    Job Manager API

    A modern job management system

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from jobmanager_client.models.register_runner_v1_runner_register_post200_response import RegisterRunnerV1RunnerRegisterPost200Response  # noqa: E501

class TestRegisterRunnerV1RunnerRegisterPost200Response(unittest.TestCase):
    """RegisterRunnerV1RunnerRegisterPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RegisterRunnerV1RunnerRegisterPost200Response:
        """Test RegisterRunnerV1RunnerRegisterPost200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RegisterRunnerV1RunnerRegisterPost200Response`
        """
        model = RegisterRunnerV1RunnerRegisterPost200Response()  # noqa: E501
        if include_optional:
            return RegisterRunnerV1RunnerRegisterPost200Response(
                id = 56,
                token = ''
            )
        else:
            return RegisterRunnerV1RunnerRegisterPost200Response(
        )
        """

    def testRegisterRunnerV1RunnerRegisterPost200Response(self):
        """Test RegisterRunnerV1RunnerRegisterPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
