# coding: utf-8

"""
    Job Manager API

    API for managing jobs and builders within the Job Manager system.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from jobmanager_client.models.v1_jobs_job_id_token_post200_response import V1JobsJobIdTokenPost200Response  # noqa: E501

class TestV1JobsJobIdTokenPost200Response(unittest.TestCase):
    """V1JobsJobIdTokenPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1JobsJobIdTokenPost200Response:
        """Test V1JobsJobIdTokenPost200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1JobsJobIdTokenPost200Response`
        """
        model = V1JobsJobIdTokenPost200Response()  # noqa: E501
        if include_optional:
            return V1JobsJobIdTokenPost200Response(
                token = ''
            )
        else:
            return V1JobsJobIdTokenPost200Response(
        )
        """

    def testV1JobsJobIdTokenPost200Response(self):
        """Test V1JobsJobIdTokenPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
