# coding: utf-8

"""
    Job Manager API

    API for managing jobs and builders within the Job Manager system.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jobmanager_client.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        self.api.api_client.close()

    def test_v1_jobs_get(self) -> None:
        """Test case for v1_jobs_get

        Retrieve jobs  # noqa: E501
        """
        pass

    def test_v1_jobs_job_id_get(self) -> None:
        """Test case for v1_jobs_job_id_get

        Retrieve job details  # noqa: E501
        """
        pass

    def test_v1_jobs_job_id_health_get(self) -> None:
        """Test case for v1_jobs_job_id_health_get

        Retrieve builder status  # noqa: E501
        """
        pass

    def test_v1_jobs_job_id_health_put(self) -> None:
        """Test case for v1_jobs_job_id_health_put

        Send builder health checks  # noqa: E501
        """
        pass

    def test_v1_jobs_job_id_put(self) -> None:
        """Test case for v1_jobs_job_id_put

        Modify a job  # noqa: E501
        """
        pass

    def test_v1_jobs_job_id_token_post(self) -> None:
        """Test case for v1_jobs_job_id_token_post

        Generate a JWT token  # noqa: E501
        """
        pass

    def test_v1_jobs_post(self) -> None:
        """Test case for v1_jobs_post

        Create a new job  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
