# coding: utf-8

"""
    Job Manager API

    A modern job management system

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from jobmanager_client.models.job_read import JobRead  # noqa: E501

class TestJobRead(unittest.TestCase):
    """JobRead unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JobRead:
        """Test JobRead
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JobRead`
        """
        model = JobRead()  # noqa: E501
        if include_optional:
            return JobRead(
                requested_by = '',
                repository_url = '',
                repository_ref = '',
                architecture = '',
                base_series = '',
                vm_dependencies = None,
                commands = [
                    null
                    ],
                secrets = { },
                environment = { },
                artifacts_dir = '',
                topology = '',
                vm_ip = '',
                vm_size = '',
                status = '',
                artifact_urls = [
                    null
                    ],
                log_urls = [
                    null
                    ],
                id = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return JobRead(
                requested_by = '',
                architecture = '',
                base_series = '',
                id = 56,
        )
        """

    def testJobRead(self):
        """Test JobRead"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
