# coding: utf-8

"""
    Job Manager API

    A modern job management system

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jobmanager_client.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        self.api.api_client.close()

    def test_health_check_health_get(self) -> None:
        """Test case for health_check_health_get

        Health Check  # noqa: E501
        """
        pass

    def test_root_get(self) -> None:
        """Test case for root_get

        Root  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
