# coding: utf-8

"""
    Job Manager API

    A modern job management system

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jobmanager_client.api.runners_api import RunnersApi  # noqa: E501


class TestRunnersApi(unittest.TestCase):
    """RunnersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RunnersApi()

    def tearDown(self) -> None:
        self.api.api_client.close()

    def test_get_runner_health_v1_runner_runner_id_health_get(self) -> None:
        """Test case for get_runner_health_v1_runner_runner_id_health_get

        Get Runner Health  # noqa: E501
        """
        pass

    def test_register_runner_v1_runner_register_post(self) -> None:
        """Test case for register_runner_v1_runner_register_post

        Register Runner  # noqa: E501
        """
        pass

    def test_update_runner_health_v1_runner_runner_id_health_put(self) -> None:
        """Test case for update_runner_health_v1_runner_runner_id_health_put

        Update Runner Health  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
