# coding: utf-8

"""
    Job Manager API

    A modern job management system

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from jobmanager_client.models.vm_dependencies import VmDependencies  # noqa: E501

class TestVmDependencies(unittest.TestCase):
    """VmDependencies unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VmDependencies:
        """Test VmDependencies
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VmDependencies`
        """
        model = VmDependencies()  # noqa: E501
        if include_optional:
            return VmDependencies(
            )
        else:
            return VmDependencies(
        )
        """

    def testVmDependencies(self):
        """Test VmDependencies"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
