# coding: utf-8

"""
    Job Manager API

    A modern job management system

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from jobmanager_client.models.get_runner_health_v1_runner_runner_id_health_get200_response import GetRunnerHealthV1RunnerRunnerIdHealthGet200Response  # noqa: E501

class TestGetRunnerHealthV1RunnerRunnerIdHealthGet200Response(unittest.TestCase):
    """GetRunnerHealthV1RunnerRunnerIdHealthGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetRunnerHealthV1RunnerRunnerIdHealthGet200Response:
        """Test GetRunnerHealthV1RunnerRunnerIdHealthGet200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetRunnerHealthV1RunnerRunnerIdHealthGet200Response`
        """
        model = GetRunnerHealthV1RunnerRunnerIdHealthGet200Response()  # noqa: E501
        if include_optional:
            return GetRunnerHealthV1RunnerRunnerIdHealthGet200Response(
                label = '',
                cpu_usage = '',
                ram_usage = '',
                disk_usage = '',
                status = '',
                deletable = True
            )
        else:
            return GetRunnerHealthV1RunnerRunnerIdHealthGet200Response(
        )
        """

    def testGetRunnerHealthV1RunnerRunnerIdHealthGet200Response(self):
        """Test GetRunnerHealthV1RunnerRunnerIdHealthGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
