# coding: utf-8

"""
    Job Manager API

    A modern job management system

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jobmanager_client.api.tokens_api import TokensApi  # noqa: E501


class TestTokensApi(unittest.TestCase):
    """TokensApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TokensApi()

    def tearDown(self) -> None:
        self.api.api_client.close()

    def test_create_api_access_token_v1_api_access_token_post(self) -> None:
        """Test case for create_api_access_token_v1_api_access_token_post

        Create Api Access Token  # noqa: E501
        """
        pass

    def test_revoke_api_access_token_v1_api_access_token_delete(self) -> None:
        """Test case for revoke_api_access_token_v1_api_access_token_delete

        Revoke Api Access Token  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
