# coding: utf-8

"""
    Job Manager API

    API for managing jobs and builders within the Job Manager system.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from jobmanager_client.models.v1_jobs_job_id_health_get200_response import V1JobsJobIdHealthGet200Response  # noqa: E501

class TestV1JobsJobIdHealthGet200Response(unittest.TestCase):
    """V1JobsJobIdHealthGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1JobsJobIdHealthGet200Response:
        """Test V1JobsJobIdHealthGet200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1JobsJobIdHealthGet200Response`
        """
        model = V1JobsJobIdHealthGet200Response()  # noqa: E501
        if include_optional:
            return V1JobsJobIdHealthGet200Response(
                label = '',
                cpu_usage = '',
                ram_usage = '',
                disk_usage = '',
                status = '',
                deletable = True
            )
        else:
            return V1JobsJobIdHealthGet200Response(
        )
        """

    def testV1JobsJobIdHealthGet200Response(self):
        """Test V1JobsJobIdHealthGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
