# coding: utf-8

"""
    Job Manager API

    API for managing jobs and builders within the Job Manager system.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from jobmanager_client.models.v1_jobs_post_request import V1JobsPostRequest  # noqa: E501

class TestV1JobsPostRequest(unittest.TestCase):
    """V1JobsPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1JobsPostRequest:
        """Test V1JobsPostRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1JobsPostRequest`
        """
        model = V1JobsPostRequest()  # noqa: E501
        if include_optional:
            return V1JobsPostRequest(
                repository_url = '',
                repository_ref = '',
                architecture = '',
                vm_dependecies = None,
                commands = [
                    ''
                    ],
                secrets = None,
                environment = None,
                artifacts_dir = '',
                topology = '',
                vm_size = ''
            )
        else:
            return V1JobsPostRequest(
        )
        """

    def testV1JobsPostRequest(self):
        """Test V1JobsPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
