# coding: utf-8

"""
    Job Manager API

    A modern job management system

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from jobmanager_client.models.update_runner_health_v1_runner_runner_id_health_put_request import UpdateRunnerHealthV1RunnerRunnerIdHealthPutRequest  # noqa: E501

class TestUpdateRunnerHealthV1RunnerRunnerIdHealthPutRequest(unittest.TestCase):
    """UpdateRunnerHealthV1RunnerRunnerIdHealthPutRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateRunnerHealthV1RunnerRunnerIdHealthPutRequest:
        """Test UpdateRunnerHealthV1RunnerRunnerIdHealthPutRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateRunnerHealthV1RunnerRunnerIdHealthPutRequest`
        """
        model = UpdateRunnerHealthV1RunnerRunnerIdHealthPutRequest()  # noqa: E501
        if include_optional:
            return UpdateRunnerHealthV1RunnerRunnerIdHealthPutRequest(
                label = '',
                cpu_usage = '',
                ram_usage = '',
                disk_usage = '',
                status = ''
            )
        else:
            return UpdateRunnerHealthV1RunnerRunnerIdHealthPutRequest(
                label = '',
                cpu_usage = '',
                ram_usage = '',
                disk_usage = '',
                status = '',
        )
        """

    def testUpdateRunnerHealthV1RunnerRunnerIdHealthPutRequest(self):
        """Test UpdateRunnerHealthV1RunnerRunnerIdHealthPutRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
