# coding: utf-8

"""
    Job Manager API

    API for managing jobs and builders within the Job Manager system.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from jobmanager_client.models.v1_jobs_job_id_token_post_request import V1JobsJobIdTokenPostRequest  # noqa: E501

class TestV1JobsJobIdTokenPostRequest(unittest.TestCase):
    """V1JobsJobIdTokenPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1JobsJobIdTokenPostRequest:
        """Test V1JobsJobIdTokenPostRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1JobsJobIdTokenPostRequest`
        """
        model = V1JobsJobIdTokenPostRequest()  # noqa: E501
        if include_optional:
            return V1JobsJobIdTokenPostRequest(
                public_key = '',
                private_key = '',
                job_id = 56
            )
        else:
            return V1JobsJobIdTokenPostRequest(
        )
        """

    def testV1JobsJobIdTokenPostRequest(self):
        """Test V1JobsJobIdTokenPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
