# coding: utf-8

"""
    Job Manager API

    A modern job management system

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from jobmanager_client.models.register_runner_v1_runner_register_post_request import RegisterRunnerV1RunnerRegisterPostRequest  # noqa: E501

class TestRegisterRunnerV1RunnerRegisterPostRequest(unittest.TestCase):
    """RegisterRunnerV1RunnerRegisterPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RegisterRunnerV1RunnerRegisterPostRequest:
        """Test RegisterRunnerV1RunnerRegisterPostRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RegisterRunnerV1RunnerRegisterPostRequest`
        """
        model = RegisterRunnerV1RunnerRegisterPostRequest()  # noqa: E501
        if include_optional:
            return RegisterRunnerV1RunnerRegisterPostRequest(
                name = '',
                series = '',
                arch = '',
                labels = [
                    ''
                    ],
                vm_size = ''
            )
        else:
            return RegisterRunnerV1RunnerRegisterPostRequest(
                name = '',
                series = '',
                arch = '',
        )
        """

    def testRegisterRunnerV1RunnerRegisterPostRequest(self):
        """Test RegisterRunnerV1RunnerRegisterPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
