# coding: utf-8

# flake8: noqa
"""
    Job Manager API

    A modern job management system

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from jobmanager_client.models.http_validation_error import HTTPValidationError
from jobmanager_client.models.job_create import JobCreate
from jobmanager_client.models.job_read import JobRead
from jobmanager_client.models.job_update import JobUpdate
from jobmanager_client.models.runner_create import RunnerCreate
from jobmanager_client.models.runner_health_response import RunnerHealthResponse
from jobmanager_client.models.runner_health_update_response import RunnerHealthUpdateResponse
from jobmanager_client.models.runner_register_response import RunnerRegisterResponse
from jobmanager_client.models.validation_error import ValidationError
from jobmanager_client.models.validation_error_loc_inner import ValidationErrorLocInner
from jobmanager_client.models.vm_dependencies import VmDependencies
