# coding: utf-8

# flake8: noqa
"""
    Job Manager API

    A modern job management system

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from jobmanager_client.models.get_runner_health_v1_runner_runner_id_health_get200_response import GetRunnerHealthV1RunnerRunnerIdHealthGet200Response
from jobmanager_client.models.http_validation_error import HTTPValidationError
from jobmanager_client.models.job_create import JobCreate
from jobmanager_client.models.job_read import JobRead
from jobmanager_client.models.job_update import JobUpdate
from jobmanager_client.models.register_runner_v1_runner_register_post200_response import RegisterRunnerV1RunnerRegisterPost200Response
from jobmanager_client.models.register_runner_v1_runner_register_post_request import RegisterRunnerV1RunnerRegisterPostRequest
from jobmanager_client.models.update_runner_health_v1_runner_runner_id_health_put_request import UpdateRunnerHealthV1RunnerRunnerIdHealthPutRequest
from jobmanager_client.models.validation_error import ValidationError
from jobmanager_client.models.validation_error_loc_inner import ValidationErrorLocInner
from jobmanager_client.models.vm_dependencies import VmDependencies
