# coding: utf-8

"""
    Job Manager API

    A modern job management system

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictStr

class UpdateRunnerHealthV1RunnerRunnerIdHealthPutRequest(BaseModel):
    """
    UpdateRunnerHealthV1RunnerRunnerIdHealthPutRequest
    """
    label: StrictStr = Field(...)
    cpu_usage: StrictStr = Field(...)
    ram_usage: StrictStr = Field(...)
    disk_usage: StrictStr = Field(...)
    status: StrictStr = Field(...)
    __properties = ["label", "cpu_usage", "ram_usage", "disk_usage", "status"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> UpdateRunnerHealthV1RunnerRunnerIdHealthPutRequest:
        """Create an instance of UpdateRunnerHealthV1RunnerRunnerIdHealthPutRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> UpdateRunnerHealthV1RunnerRunnerIdHealthPutRequest:
        """Create an instance of UpdateRunnerHealthV1RunnerRunnerIdHealthPutRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return UpdateRunnerHealthV1RunnerRunnerIdHealthPutRequest.parse_obj(obj)

        _obj = UpdateRunnerHealthV1RunnerRunnerIdHealthPutRequest.parse_obj({
            "label": obj.get("label"),
            "cpu_usage": obj.get("cpu_usage"),
            "ram_usage": obj.get("ram_usage"),
            "disk_usage": obj.get("disk_usage"),
            "status": obj.get("status")
        })
        return _obj


