# coding: utf-8

"""
    Job Manager API

    API for managing jobs and builders within the Job Manager system.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictStr
from jobmanager_client.models.v1_jobs_post201_response_maintenance import V1JobsPost201ResponseMaintenance

class V1JobsPost201Response(BaseModel):
    """
    V1JobsPost201Response
    """
    status_url: Optional[StrictStr] = None
    maintenance: Optional[V1JobsPost201ResponseMaintenance] = None
    __properties = ["status_url", "maintenance"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> V1JobsPost201Response:
        """Create an instance of V1JobsPost201Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of maintenance
        if self.maintenance:
            _dict['maintenance'] = self.maintenance.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> V1JobsPost201Response:
        """Create an instance of V1JobsPost201Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return V1JobsPost201Response.parse_obj(obj)

        _obj = V1JobsPost201Response.parse_obj({
            "status_url": obj.get("status_url"),
            "maintenance": V1JobsPost201ResponseMaintenance.from_dict(obj.get("maintenance")) if obj.get("maintenance") is not None else None
        })
        return _obj


