# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

copilot:
  # The version of the toolkit to use (matches a Release Tag in this repo)
  version: "v0.5.0"
  # The collections you want to install
  collections:
    - charm-python
    - pfe-charms
