{
 "title": "GitHub Self-Hosted Runner Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Runners Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({filename=\"/var/log/github-runner-metrics.log\"} | json event=\"event\" | event = `runner_start` [$__range])",
     "legendFormat": "Started"
    },
    {
     "expr": "count_over_time({filename=\"/var/log/github-runner-metrics.log\"} | json event=\"event\" | event = `runner_installed` [$__range])",
     "legendFormat": "Initialized"
    }
   ]
  },
  {
   "title": "Runner Idle Duration in seconds",
   "type": "timeseries",
   "description": "All aggregations are based on a 1-hour time period.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time({filename=\"/var/log/github-runner-metrics.log\"} | json event=\"event\", idle=\"idle\" | event = `runner_start` | unwrap idle [1h])",
     "legendFormat": "Average"
    },
    {
     "expr": "max_over_time({filename=\"/var/log/github-runner-metrics.log\"} | json event=\"event\", idle=\"idle\" | event = `runner_start` | unwrap duration [1h])",
     "legendFormat": "Max"
    },
    {
     "expr": "min_over_time({filename=\"/var/log/github-runner-metrics.log\"} | json event=\"event\", idle=\"idle\" | event = `runner_start` | unwrap duration [1h])",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Runner Installation Duration in seconds",
   "type": "timeseries",
   "description": "All aggregations are based on a 1-hour time period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg_over_time({filename=\"/var/log/github-runner-metrics.log\"} | json event=\"event\", duration=\"duration\" | event = `runner_installed` | unwrap duration [1h])",
     "legendFormat": "Average"
    },
    {
     "expr": "max_over_time({filename=\"/var/log/github-runner-metrics.log\"} | json event=\"event\", duration=\"duration\" | event = `runner_installed` | unwrap duration [1h])",
     "legendFormat": "Max"
    },
    {
     "expr": "min_over_time({filename=\"/var/log/github-runner-metrics.log\"} | json event=\"event\", duration=\"duration\" | event = `runner_installed` | unwrap duration [1h])",
     "legendFormat": "Max"
    }
   ]
  }
 ]
}