# coding: utf-8

"""
    Job Manager API

    API for managing jobs and builders within the Job Manager system.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from jobmanager_client.models.v1_jobs_post201_response_maintenance import V1JobsPost201ResponseMaintenance  # noqa: E501

class TestV1JobsPost201ResponseMaintenance(unittest.TestCase):
    """V1JobsPost201ResponseMaintenance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1JobsPost201ResponseMaintenance:
        """Test V1JobsPost201ResponseMaintenance
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1JobsPost201ResponseMaintenance`
        """
        model = V1JobsPost201ResponseMaintenance()  # noqa: E501
        if include_optional:
            return V1JobsPost201ResponseMaintenance(
                kind = '',
                message = ''
            )
        else:
            return V1JobsPost201ResponseMaintenance(
        )
        """

    def testV1JobsPost201ResponseMaintenance(self):
        """Test V1JobsPost201ResponseMaintenance"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
