# coding: utf-8

"""
    Job Manager API

    API for managing jobs and builders within the Job Manager system.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from jobmanager_client.models.v1_jobs_job_id_health_get200_response import V1JobsJobIdHealthGet200Response  # noqa: E501

class TestV1JobsJobIdHealthGet200Response(unittest.TestCase):
    """V1JobsJobIdHealthGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1JobsJobIdHealthGet200Response:
        """Test V1JobsJobIdHealthGet200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1JobsJobIdHealthGet200Response`
        """
        model = V1JobsJobIdHealthGet200Response()  # noqa: E501
        if include_optional:
            return V1JobsJobIdHealthGet200Response(
                label = '',
                cpu_usage = '',
                ram_usage = '',
                disk_usage = '',
                status = '',
                job = jobmanager_client.models.job.Job(
                    job_id = 56, 
                    requested_by = '', 
                    repository_url = '', 
                    repository_ref = '', 
                    architecture = '', 
                    base_series = '', 
                    vm_dependencies = jobmanager_client.models.vm_dependencies.vm_dependencies(), 
                    commands = [
                        ''
                        ], 
                    secrets = jobmanager_client.models.secrets.secrets(), 
                    environment = jobmanager_client.models.environment.environment(), 
                    artifacts_dir = '', 
                    topology = '', 
                    vm_ip = '', 
                    vm_size = 'S', 
                    status = 'PENDING', 
                    artifact_urls = [
                        ''
                        ], 
                    log_url = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return V1JobsJobIdHealthGet200Response(
        )
        """

    def testV1JobsJobIdHealthGet200Response(self):
        """Test V1JobsJobIdHealthGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
