# coding: utf-8

"""
    Job Manager API

    A modern job management system

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import re  # noqa: F401
import io
import warnings

from pydantic import validate_arguments, ValidationError

from pydantic import StrictInt

from jobmanager_client.models.runner_create import RunnerCreate
from jobmanager_client.models.runner_health_response import RunnerHealthResponse
from jobmanager_client.models.runner_health_update_response import RunnerHealthUpdateResponse
from jobmanager_client.models.runner_register_response import RunnerRegisterResponse

from jobmanager_client.api_client import ApiClient
from jobmanager_client.api_response import ApiResponse
from jobmanager_client.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)


class RunnersApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_arguments
    def get_runner_health_v1_runners_runner_id_health_get(self, runner_id : StrictInt, **kwargs) -> RunnerHealthResponse:  # noqa: E501
        """Get Runner Health  # noqa: E501

        Get runner health status.  Args:     runner_id: Unique identifier of the runner     db: Database session dependency  Returns:     dict: Runner health metrics including CPU, RAM, disk usage and status  Raises:     HTTPException 404: If runner is not found  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_runner_health_v1_runners_runner_id_health_get(runner_id, async_req=True)
        >>> result = thread.get()

        :param runner_id: (required)
        :type runner_id: int
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: RunnerHealthResponse
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the get_runner_health_v1_runners_runner_id_health_get_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.get_runner_health_v1_runners_runner_id_health_get_with_http_info(runner_id, **kwargs)  # noqa: E501

    @validate_arguments
    def get_runner_health_v1_runners_runner_id_health_get_with_http_info(self, runner_id : StrictInt, **kwargs) -> ApiResponse:  # noqa: E501
        """Get Runner Health  # noqa: E501

        Get runner health status.  Args:     runner_id: Unique identifier of the runner     db: Database session dependency  Returns:     dict: Runner health metrics including CPU, RAM, disk usage and status  Raises:     HTTPException 404: If runner is not found  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_runner_health_v1_runners_runner_id_health_get_with_http_info(runner_id, async_req=True)
        >>> result = thread.get()

        :param runner_id: (required)
        :type runner_id: int
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(RunnerHealthResponse, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'runner_id'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_runner_health_v1_runners_runner_id_health_get" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['runner_id'] is not None:
            _path_params['runner_id'] = _params['runner_id']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            '200': "RunnerHealthResponse",
            '422': "HTTPValidationError",
        }

        return self.api_client.call_api(
            '/v1/runners/{runner_id}/health', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def register_runner_v1_runners_register_post(self, runner_create : RunnerCreate, **kwargs) -> RunnerRegisterResponse:  # noqa: E501
        """Register Runner  # noqa: E501

        Register a new runner.  Args:     runner_in: Runner registration data including name and labels     db: Database session dependency     token: API access token for authorization  Returns:     dict: Contains the runner ID and its authentication token  Raises:     HTTPException 500: If token generation fails  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.register_runner_v1_runners_register_post(runner_create, async_req=True)
        >>> result = thread.get()

        :param runner_create: (required)
        :type runner_create: RunnerCreate
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: RunnerRegisterResponse
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the register_runner_v1_runners_register_post_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.register_runner_v1_runners_register_post_with_http_info(runner_create, **kwargs)  # noqa: E501

    @validate_arguments
    def register_runner_v1_runners_register_post_with_http_info(self, runner_create : RunnerCreate, **kwargs) -> ApiResponse:  # noqa: E501
        """Register Runner  # noqa: E501

        Register a new runner.  Args:     runner_in: Runner registration data including name and labels     db: Database session dependency     token: API access token for authorization  Returns:     dict: Contains the runner ID and its authentication token  Raises:     HTTPException 500: If token generation fails  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.register_runner_v1_runners_register_post_with_http_info(runner_create, async_req=True)
        >>> result = thread.get()

        :param runner_create: (required)
        :type runner_create: RunnerCreate
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(RunnerRegisterResponse, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'runner_create'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method register_runner_v1_runners_register_post" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['runner_create'] is not None:
            _body_params = _params['runner_create']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['application/json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            '200': "RunnerRegisterResponse",
            '422': "HTTPValidationError",
        }

        return self.api_client.call_api(
            '/v1/runners/register', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def update_runner_health_v1_runners_runner_id_health_put(self, runner_id : StrictInt, **kwargs) -> RunnerHealthUpdateResponse:  # noqa: E501
        """Update Runner Health  # noqa: E501

        Update runner health metrics.  Args:     runner_id: Unique identifier of the runner     request: FastAPI request object containing health metrics     db: Database session dependency     token: Runner token for authorization  Returns:     dict: Success indicator  Raises:     HTTPException 404: If runner is not found  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.update_runner_health_v1_runners_runner_id_health_put(runner_id, async_req=True)
        >>> result = thread.get()

        :param runner_id: (required)
        :type runner_id: int
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: RunnerHealthUpdateResponse
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the update_runner_health_v1_runners_runner_id_health_put_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.update_runner_health_v1_runners_runner_id_health_put_with_http_info(runner_id, **kwargs)  # noqa: E501

    @validate_arguments
    def update_runner_health_v1_runners_runner_id_health_put_with_http_info(self, runner_id : StrictInt, **kwargs) -> ApiResponse:  # noqa: E501
        """Update Runner Health  # noqa: E501

        Update runner health metrics.  Args:     runner_id: Unique identifier of the runner     request: FastAPI request object containing health metrics     db: Database session dependency     token: Runner token for authorization  Returns:     dict: Success indicator  Raises:     HTTPException 404: If runner is not found  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.update_runner_health_v1_runners_runner_id_health_put_with_http_info(runner_id, async_req=True)
        >>> result = thread.get()

        :param runner_id: (required)
        :type runner_id: int
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(RunnerHealthUpdateResponse, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'runner_id'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_runner_health_v1_runners_runner_id_health_put" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['runner_id'] is not None:
            _path_params['runner_id'] = _params['runner_id']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            '200': "RunnerHealthUpdateResponse",
            '422': "HTTPValidationError",
        }

        return self.api_client.call_api(
            '/v1/runners/{runner_id}/health', 'PUT',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))
