{
 "title": "GitHub Self-Hosted Runner Metrics (Long-Term)",
 "description": "This dashboard visualises metrics about runners that are suitable for display over a longer time interval.",
 "time": { "from": "now-29d", "to": "now" },
 "templating": {
  "list": [
   { "name": "lokids", "label": "Loki datasource", "query": "loki" },
   { "name": "prometheusds", "label": "Prometheus datasource", "query": "prometheus" },
   {
    "name": "juju_unit",
    "label": "Juju unit",
    "query": {}
   },
   {
    "name": "juju_application",
    "label": "Juju application",
    "query": {}
   },
   {
    "name": "juju_model_uuid",
    "label": "Juju model uuid",
    "query": {}
   },
   {
    "name": "juju_model",
    "label": "Juju model",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Jobs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({filename=\"/var/log/github-runner-metrics.log\"} | json event=\"event\" | event = \"runner_start\" [$__range]))"
    }
   ]
  },
  {
   "title": "Total Repositories",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (repo) (count_over_time({filename=\"/var/log/github-runner-metrics.log\"} | json event=\"event\" | event = \"runner_start\" | json repo=\"repo\" [$__range])))"
    }
   ]
  },
  {
   "title": "Jobs per day",
   "type": "timeseries",
   "description": "Each point visualises the aggregation of the last 24 hours.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(filename)(count_over_time({filename=\"/var/log/github-runner-metrics.log\", juju_application=~\"$juju_application\", juju_model=~\"$juju_model\", juju_model_uuid=~\"$juju_model_uuid\", juju_unit=~\"$juju_unit\"} | json event=\"event\" | event=\"runner_start\"[1d]))",
     "legendFormat": "Started",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Percentage of Jobs with Low Queue Time",
   "type": "stat",
   "description": "Percentage of jobs queued for less than 60 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({filename=\"/var/log/github-runner-metrics.log\"} | json event=\"event\",duration=\"queue_duration\" |  event=\"runner_start\" | duration < 60 | __error__=\"\" [$__range])) / sum(count_over_time({filename=\"/var/log/github-runner-metrics.log\"} | json event=\"event\",duration=\"queue_duration\" |  event=\"runner_start\" | duration >= 0 | __error__=\"\" [$__range])) * 100"
    }
   ]
  }
 ]
}