name: Build image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build-container-image:
    name: Build runner image for containers
    runs-on: [self-hosted, large]
    steps:
      - uses: canonical/setup-lxd@main
        with:
          channel: 5.19/stable
      - uses: actions/checkout@v4
      - name: Start runner container
        run: /snap/bin/lxc launch ubuntu-daily:jammy runner
      - name: Run build script
        run: bash scripts/build-image.sh
      - name: Publish runner container as image
        run: /snap/bin/lxc publish runner --alias runner --reuse -f && /snap/bin/lxc image export runner ./runner-image
      - uses: actions/upload-artifact@v3
        with:
          name: self-hosted-runner-image-container
          path: ./runner-image.tar.gz
          retention-days: 14
          if-no-files-found: error
  integration-tests:
    name: Integration test
    needs: build-container-image
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      juju-channel: 3.1/stable
      pre-run-script: scripts/pre-integration-test.sh
      provider: lxd
      test-tox-env: integration-juju3.1
      modules: '["test_charm_fork_repo", "test_charm_no_runner", "test_charm_scheduled_events", "test_charm_one_runner", "test_charm_metrics", "test_self_hosted_runner", "test_charm_with_proxy"]'
  build-image:
    name: Build runner image for virtual machine
    needs: integration-tests
    runs-on: [self-hosted, large]
    steps:
      - uses: canonical/setup-lxd@main
        with:
          channel: 5.19/stable
      - uses: actions/checkout@v4
      - name: Start runner VM
        run: /snap/bin/lxc launch ubuntu-daily:jammy runner --vm
      - name: Run build script
        run: bash scripts/build-image.sh
      - name: Publish runner container as image
        run: /snap/bin/lxc publish runner --alias runner --reuse -f && /snap/bin/lxc image export runner./runner-image --vm
      - uses: actions/upload-artifact@v3
        with:
          name: self-hosted-runner-image 
          path: ./runner-image.tar.gz
          retention-days: 14
          if-no-files-found: error
