name: Comment on the pull request

on:
  pull_request:
    types:
      - opened
    branches:
      - 'track/**'

jobs:
  comment-on-pr:
    uses: canonical/operator-workflows/.github/workflows/comment_contributing.yaml@main
    secrets: inherit
    steps:
      - name: Add dynamic PR comment with status
        run: |
          pr_url="https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
          message="🚀 PR opened by @${{ github.actor }}. Current PR status: *${{ github.event.pull_request.state }}*."
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d "{\"body\":\"$message\"}" $pr_url  
