name: Openstack  tests
  
on:
  pull_request:

jobs:
  openstack-integration-tests-private-endpoint:
    name: Openstack integration test using private-endpoint
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      juju-channel: 3.2/stable
      pre-run-script: scripts/setup-lxd.sh
      provider: lxd
      test-tox-env: integration-juju3.2
      modules: '["test_runner_manager_openstack"]'
      extra-arguments: "-m openstack"
      self-hosted-runner: true
      self-hosted-runner-label: stg-private-endpoint
