name: Promote charm

on:
  workflow_dispatch:
    inputs:
      base-architecture:
        type: choice
        description: 'Architecture of the charm to promote'
        options:
        - amd64
        - arm64
      origin-channel:
        type: choice
        description: 'Origin Channel'
        options:
        - latest/beta
        - latest/edge
        - 1/edge
      destination-channel:
        type: choice
        description: 'Destination Channel'
        options:
        - latest/stable
        - latest/beta
        - 1/stable
    secrets:
      CHARMHUB_TOKEN:
        required: true

jobs:
  promote-charm:
    uses: canonical/operator-workflows/.github/workflows/promote_charm.yaml@main
    with:
      origin-channel: ${{ github.event.inputs.origin-channel }}
      destination-channel: ${{ github.event.inputs.destination-channel }}
      doc-automation-disabled: false
      base-architecture: ${{ github.event.inputs.base-architecture }}
    secrets: inherit
