name: Publish to edge

on:
  push:
    branches:
      - main
      - track/*
      - test/multi-publish

jobs:
  publish-to-edge:
    uses: canonical/operator-workflows/.github/workflows/publish_charm.yaml@fix/deduplicate-artefacts
    secrets: inherit
