name: Push Event Tests

on:
  push:
    branches:
      - push-e2e-*

jobs:
  push-event-tests:
    runs-on: [self-hosted, linux, "${{ github.ref_name }}"]
    steps:
      - name: Echo runner name
        run: |
          echo "Hello, runner: ${{ github.ref_name }}"
