name: CI
on: [push]
jobs:
  build:
    env:
      DISCOURSE_API_KEY: ${{ secrets.DISCOURSE_API_KEY }}
      DISCOURSE_API_USERNAME: ${{ secrets.DISCOURSE_API_USERNAME }}
    runs-on: [self-hosted, stg-private-endpoint]
    steps:
    - uses: actions/checkout@v3
    - name: Setup tmate session
      uses: canonical/action-tmate@main
