name: Schedule Event Tests

on:
  workflow_dispatch:  # Replaced by end-to-end test to match 'schedule'

jobs:

  extract-runner-name:
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.extract-runner-name.outputs.name }}
    steps:
      - name: Extract runner name
        id: extract-runner-name
        run: |
          REPO=${{ github.repository }}
          RUNNER_NAME=${REPO#${{ github.repository_owner }}/}
          echo name=$RUNNER_NAME >> $GITHUB_OUTPUT

  schedule-event-tests:
    needs: [ extract-runner-name ]
    runs-on: [ self-hosted, linux, x64, "${{ needs.extract-runner-name.outputs.name }}" ]
    steps:
      - name: Echo runner name
        run: |
          echo "Hello, runner:  ${{ needs.extract-runner-name.outputs.name }}"
