name: Start E2E Test

on:
  pull_request:

jobs:
  deploy-e2e-test-runner:
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v3
#
#      - name: Setup LXD
#        uses: canonical/setup-lxd@main
#
#      - name: Install charmcraft
#        run: sudo snap install charmcraft --classic
#
#      - name: Install juju
#        run: sudo snap install juju --channel=3.1/stable
#
#      - name: Pack github-runner Charm
#        run: charmcraft pack
#
#      - name: Bootstrap Juju LXD controller
#        run: juju bootstrap lxd
#
#      - name: Create Testing Juju Model
#        run: juju add-model testing
#
#      - run: juju status
#
#      - name: Setting Testing Model Constraints
#        run: juju set-model-constraints "virt-type=virtual-machine mem=16G cores=4"
#
#      - name: Change Testing Model Logging Level
#        run: juju model-config logging-config="<root>=INFO;unit=DEBUG"
#
#      - name: Deploy github-runner Charm
#        run: |
#          juju deploy ./github-runner_ubuntu-22.04-amd64.charm e2e-${{ github.run_id }}-${{ github.run_number }} \
#            --config path=canonical/github-runner-operator \
#            --config token=${{ secrets.E2E_TESTING_TOKEN }} \
#            --config virtual-machines=1

      - name: Install GitHub Cli
        run: which gh || sudo apt install gh -y

      - name: Dispatch Workflow on Testing Runner
        env:
          GH_TOKEN: ${{ secrets.E2E_TESTING_TOKEN }}
        run: |
          set +x
          MAIN_SHA=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ secrets.E2E_TESTING_REPO }}/git/ref/heads/main --jq .object.sha)
          
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ secrets.E2E_TESTING_REPO }}/git/refs \
            -f ref='refs/heads/e2e-${{ github.run_id }}-${{ github.run_number }}' \
            -f sha=$MAIN_SHA
          
          gh workflow run test.yaml \
            -R ${{ secrets.E2E_TESTING_REPO }} \
            --ref e2e-${{ github.run_id }}-${{ github.run_number }} \
            -f runner=e2e-${{ github.run_id }}-${{ github.run_number }}
          
          gh run list \
            --workflow=test.yaml \
            -R ${{ secrets.E2E_TESTING_REPO }} \
            -b e2e-${{ github.run_id }}-${{ github.run_number }} \
            --json workflowDatabaseId,status
          
          get_workflow_status() {
              output=$(gh run list \
                        --workflow=test.yaml \
                        -R ${{ secrets.E2E_TESTING_REPO }} \
                        -b e2e-${{ github.run_id }}-${{ github.run_number }} \
                        --json workflowDatabaseId,status)

              if [ $(echo "$output" | jq 'length') -eq 0 ]
              then
                  echo "not-started"
              else
                  # Parse output with jq to get the status field of the first object
                  status=$(echo "$output" | jq -r '.[0].status')
                  echo "$status"
              fi
          }
          
          for i in {1..20}
          do
              get_workflow_status
              sleep 1
          done