name: Start E2E Test

on:
  pull_request:

jobs:
  deploy-e2e-test-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup LXD
        uses: canonical/setup-lxd@main

      - name: Install charmcraft
        run: sudo snap install charmcraft --classic

      - name: Install juju
        run: sudo snap install juju --channel=3.1/stable

      - name: Pack github-runner Charm
        run: charmcraft pack

      - name: Bootstrap Juju LXD controller
        run: juju bootstrap lxd

      - name: Create Testing Juju Model
        run: juju add-model testing

      - run: juju status


#      - name: Deploy github-runner Charm
#        run: |
#          juju deploy ./github-runner_ubuntu-22.04-amd64.charm e2e-${{ github.run_id }}-${{ github.run_number }} \
#            --config=
