name: Staging Tests
on: [push, pull_request]
jobs:
  staging-tests:
    strategy:
      matrix:
        arch: [arm64, x64]
    runs-on: ["self-hosted", "staging", "${{ matrix.arch }}"]
    steps:
        - name: Hello world
          run: |
            echo "Hello, world"
