name: Staging Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ["self-hosted", "staging", "ps7"]
    steps:
        - name: Hello world
          run: |
            echo "Hello, world"
        - name: Git pull via git
          run: |
            git clone git://git.launchpad.net/ntp-charm  ntp-charm-via-git
        - name: Github pull via ssh
          run: |
            git clone git@github.com:canonical/github-runner-operator.git github-runner-operator-via-ssh || true
        - name: Git pull via ssh
          run: |
            git clone git+ssh://git.launchpad.net/ntp-charm ntp-charm-via-ssh || true
        - name: egress var
          run: |
                echo $EGRESS_PROXY
                cat /etc/environment
                env
        - name: show ip address
          run: |
                ip addr show
        - name: sleep 20 minutes
          run: |
                    sleep 1200