name: Staging Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ["self-hosted", "staging", "ps7"]
    steps:
        - name: Hello world
          run: |
            echo "Hello, world"
        - name: Git pull via ssh
          run: |
            git clone git@github.com:canonical/github-runner-operator.git
