name: Temporary Schedule Event Tests

on:
  schedule:
    - cron: '* */1 * * *'

jobs:
  schedule-event-tests:
    runs-on: [ self-hosted, linux, X64, large, jammy ]
    steps:
      - name: Echo Hello World
        run: |
          echo "Hello, world!"
