name: test charmedhpc runner
on: [push]
jobs:
  ssdlc-scan:
    name: Run SBOM Scan
    runs-on: [self-hosted, linux, xlarge, amd64, self-hosted-linux-amd64-noble-xlarge]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test SBOM Service Connectivity
        run: |
          for i in {1..5}; do
          echo "Attempt $i..."
          # Get the proxy address from the aproxy snap and use it for the curl request
          curl -x http://$(sudo snap get aproxy proxy) \
              -Iv --max-time 10 \
              https://sbom-request.canonical.com
          sleep 1
        done