name: Tests

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  unit-tests:
    uses: canonical/operator-workflows/.github/workflows/test.yaml@main
    secrets: inherit
    with:
      vale-style-check: false
