name: trivy

on:
  pull_request:
  workflow_dispatch:
  push:

jobs:
  trivy:
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      trivy-image-config: trivy.yaml