name: Workflow Dispatch Tests

on:
  # Manually dispatched workflow action
  workflow_dispatch:
    inputs:
      runner:
        description: 'Self hosted gh runner'
        required: true

jobs:
  workflow-dispatch-tests:
    runs-on: [self-hosted, linux, "${{ inputs.runner }}"]
    steps:
      - name: Echo input variable and message
        run: |
          echo "Hello, runner: ${{ inputs.runner }}"
      - name: Always echo a message
        if: always()
        run: echo "Should not echo if pre-job script failed"
