name: Workflow Dispatch Failure Tests 2a34f8b1-41e4-4bcb-9bbf-7a74e6c482f7

# This workflow is for testing only.
# Self-hosted runner managed by the charm is setup to fail this workflow at pre-job step.

on:
  # Manually dispatched workflow action
  workflow_dispatch:
    inputs:
      runner:
        description: 'Self hosted gh runner'
        required: true

jobs:
  workflow-dispatch-tests:
    runs-on: [self-hosted, linux, "${{ inputs.runner }}"]
    steps:
      - name: Echo input variable and message
        run: |
          echo "Hello, runner: ${{ inputs.runner }}"
      - name: Always echo a message
        if: always()
        run: echo "Should not echo if pre-job script failed"
