name: Workflow Dispatch Tests

on:
  # Manually dispatched workflow action
  workflow_dispatch:
    inputs:
      runner:
        description: 'Self hosted gh runner'
        required: true
jobs:
  workflow-dispatch-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world of workflow dispatches!
